---
language: cpp

env:
  global:
    - MAKEFLAGS = "-j 2"

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: gcc
    - os: osx
      compiler: clang
addons:
  apt:
    packages:
      - python3-dev
      - libxml2-dev
      - libfltk1.3-dev
      - fluid
      - libjpeg-dev
      - libglm-dev
      - libcminpack-dev
      - libglew-dev
      - swig
      - doxygen
      - graphviz
      - texlive-latex-base
script:
  - mkdir build buildlibs;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
     cd build;
     cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="~/OpenVSP_Install" -DVSP_INSTALL_API_TEST=true ../SuperProject;
     make;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
     cd $TRAVIS_BUILD_DIR/buildlibs;
     cmake -DCMAKE_BUILD_TYPE=Release -DVSP_USE_SYSTEM_LIBXML2=true -DVSP_USE_SYSTEM_FLTK=true -DVSP_USE_SYSTEM_GLM=true -DVSP_USE_SYSTEM_GLEW=true -DVSP_USE_SYSTEM_CMINPACK=true -DVSP_USE_SYSTEM_CPPTEST=false ../Libraries;
     make;
     cd $TRAVIS_BUILD_DIR/build;
     cmake -DCMAKE_BUILD_TYPE=Release -DVSP_CPACK_GEN=DEB -DVSP_LIBRARY_PATH=$TRAVIS_BUILD_DIR/buildlibs ../src;
     make package;
     DEBFILE=$TRAVIS_BUILD_DIR/build/OpenVSP-*-Linux.deb;
     ls $DEBFILE && echo "DEB CREATION SUCCESSFUL" || echo "DEB CREATION FAILED";
    fi
